---

- name: Create a directory if it does not exist
  ansible.builtin.file:
  path: "{{ repo_path }}"
  state: directory
  
- name: Check if the directories exist
  stat:
    path: "{{ repo_path }}/{{ item }}"
  loop: "{{ github_repos }}"
  register: directory_check_results

- name: Clone a repository
  shell:
    cmd: "git clone git@github.com:lucasbonanni/{{item.item}}.git {{ repo_path }}/{{item.item}}"
  when: not item.stat.exists
  loop: "{{ directory_check_results.results }}"